name: Main Branch Protection from RecoveryTextApp branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} == RecoveryTextApp ]]; 
          then
            echo "Error: Pull request must NOT come from 'RecoveryTextApp' branch"
            exit 1
          fi
